"""create session table

Revision ID: 01150f7268c9
Revises: 688e9ad282b8
Create Date: 2026-05-04 13:03:02.469394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (required by autogenerated SQLModel column types)


# revision identifiers, used by Alembic.
revision: str = '01150f7268c9'
down_revision: Union[str, Sequence[str], None] = '688e9ad282b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_episodes', sa.Integer(), nullable=False),
    sa.Column('episode_duration', sa.Float(), nullable=False),
    sa.Column('reset_duration', sa.Float(), nullable=False),
    sa.Column('current_episode', sa.Integer(), nullable=False),
    sa.Column('backend_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_size_bytes', sa.Integer(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
