"""create device_fault table

Revision ID: a3f1c9d24b70
Revises: 01150f7268c9
Create Date: 2026-07-11 18:40:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (required by autogenerated SQLModel column types)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a3f1c9d24b70'
down_revision: Union[str, Sequence[str], None] = '01150f7268c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'device_fault',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('system_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('system_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('device_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('parts_needed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('reported_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('reported_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('resolved_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('device_fault')
