"""create work_session and break_event tables

Revision ID: b7e2d5f8c199
Revises: a3f1c9d24b70
Create Date: 2026-07-11 19:05:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (required by autogenerated SQLModel column types)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7e2d5f8c199'
down_revision: Union[str, Sequence[str], None] = 'a3f1c9d24b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'work_session',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('operator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('operator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'break_event',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('work_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_break_event_work_session_id', 'break_event', ['work_session_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_break_event_work_session_id', table_name='break_event')
    op.drop_table('break_event')
    op.drop_table('work_session')
