"""create episode_record table

Revision ID: c4a9f1e6d3b2
Revises: b7e2d5f8c199
Create Date: 2026-07-11 19:30:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (required by autogenerated SQLModel column types)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4a9f1e6d3b2'
down_revision: Union[str, Sequence[str], None] = 'b7e2d5f8c199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'episode_record',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('work_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('operator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('recording_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('episode_index', sa.Integer(), nullable=False),
        sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('duration_s', sa.Float(), nullable=False),
        sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_episode_record_work_session_id', 'episode_record', ['work_session_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_episode_record_work_session_id', table_name='episode_record')
    op.drop_table('episode_record')
