"""add issue_class to device_fault

Distinguishes hardware faults (the original meaning of the table) from
software issues, both reported through the same flow. Existing rows are
back-filled to "hardware", which is what they all were.

Revision ID: d5b3e1a97c42
Revises: c4a9f1e6d3b2
Create Date: 2026-07-15 21:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (required by autogenerated SQLModel column types)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd5b3e1a97c42'
down_revision: Union[str, Sequence[str], None] = 'c4a9f1e6d3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default back-fills existing rows to "hardware"; kept as the column
    # default so inserts that omit it (older code paths) stay valid.
    op.add_column(
        'device_fault',
        sa.Column(
            'issue_class',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='hardware',
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('device_fault', 'issue_class')
