"""create telemetry_sample, session_run and error_event tables

Revision ID: e6c2b840f371
Revises: d5b3e1a97c42
Create Date: 2026-08-13 14:05:00.000000

Three tables behind the hourly CSV digest. All additive: nothing existing is
altered, so a machine that has already been seeded picks these up without any
data migration.

Nullable columns here carry meaning. On `telemetry_sample` a null motion column
means "not sampled" — arm and base state is only readable while a recorder holds
the hardware — as distinct from 0.0, meaning sampled and genuinely still. On
`session_run`, a null `ended_at` means the run is still in progress.
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (required by autogenerated SQLModel column types)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6c2b840f371'
down_revision: Union[str, Sequence[str], None] = 'd5b3e1a97c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'telemetry_sample',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('window_s', sa.Float(), nullable=False),
        sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('session_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('current_episode', sa.Integer(), nullable=False),
        sa.Column('machine_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('operator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('battery', sa.JSON(), nullable=True),
        sa.Column('battery_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('arms_active_s', sa.Float(), nullable=True),
        sa.Column('base_active_s', sa.Float(), nullable=True),
        sa.Column('rail_active_s', sa.Float(), nullable=True),
        sa.Column('base_distance_m', sa.Float(), nullable=True),
        sa.Column('disk_free_bytes', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_telemetry_sample_ts', 'telemetry_sample', ['ts'])

    op.create_table(
        'session_run',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('system_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('duration_s', sa.Float(), nullable=True),
        sa.Column('end_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('episodes_done', sa.Integer(), nullable=False),
        sa.Column('error_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_session_run_session_id', 'session_run', ['session_id'])

    op.create_table(
        'error_event',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('controller_log', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('session_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('raw_tail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('suppressed_count', sa.Integer(), nullable=False),
        sa.Column('alert_sent_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_error_event_ts', 'error_event', ['ts'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_error_event_ts', table_name='error_event')
    op.drop_table('error_event')
    op.drop_index('ix_session_run_session_id', table_name='session_run')
    op.drop_table('session_run')
    op.drop_index('ix_telemetry_sample_ts', table_name='telemetry_sample')
    op.drop_table('telemetry_sample')
