"""add task to session

Persists the natural-language task prompt an operator enters for a
recording session (the LeRobot `task`). Seeds the task embedded into each
episode's MCAP metadata at record start and is the default for every episode
unless the operator changes the live task mid-session. Existing rows
back-fill to "" (no task → converter falls back to its task_name).

Revision ID: e6c4a2b81f30
Revises: d5b3e1a97c42
Create Date: 2026-07-20 10:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (required by autogenerated SQLModel column types)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6c4a2b81f30'
down_revision: Union[str, Sequence[str], None] = 'd5b3e1a97c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default "" back-fills existing sessions (which had no task) and
    # keeps inserts that omit it valid.
    op.add_column(
        'session',
        sa.Column(
            'task',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='',
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('session', 'task')
